### ISSUE TITLE
Error reporting breaks parsable format

### ISSUE THREAD

**Issue by Cendio-Zeijlon** [netromdk/vermin#150]
**Describe the bug**
The error reporting in parser.py -> detect(self, config) breaks the parsable format that vermin outputs when using the argument --format parsable.

**To Reproduce**
Run vermin --format parsable foo.py

```
# foo.py
print("print)
```

The output line that reports information about the syntax error,
```
foo.py:1:7:~2, ~3:error: unterminated string literal (detected at line 1): print("print)
```
has a comma between the version tags.

**Expected behavior**
There should be a colon between the version tags.

**Environment (please complete the following information):**
version 1.5.1

**Additional context**
Can be solved by adding an additional argument `":"` to version_strings on line 99 in parser.py
```
versions = version_strings(min_versions, ":") + ":" if parsable else ""
```

**Comment by netromdk** [comment]
Thank you for reporting this! I will look into this soon.

**Comment by netromdk** [comment]
It has been fixed now. Thanks again, @Cendio-Zeijlon!

Going to release 1.5.2 soonish.
