### ISSUE TITLE
Instead of `./vermin`, `vermin` worked for macos.

### ISSUE THREAD

**Issue by earik87** [netromdk/vermin#158]
**Is your feature request related to a problem? Please describe.**
When I was reading documentation, it is confusing that I was trying to use `./vermin` but do not work for me. 
I am using MacOS with bash in terminal and `vermin` works for my case.

**Describe the solution you'd like**
Documentation could be updated, accordingly.

**Comment by netromdk** [comment]
Thank you for reaching out.

I will try to improve the wording.
