### ISSUE TITLE
Incorrectly marks python version when code has if statement/hasattr check

### ISSUE THREAD

**Issue by vikahl** [netromdk/vermin#16]
**Describe the bug**
Vermin incorrectly marks code as requiring >= 3.6 when conditionals handles earlier python versions as well.

From Paho MQTT (client.py), the `if hasattr(` allows for prior versions to 3.6 as well.

```python
        # Create SSLContext object
        if tls_version is None:
            tls_version = ssl.PROTOCOL_TLSv1
            # If the python version supports it, use highest TLS version automatically
            if hasattr(ssl, "PROTOCOL_TLS"):
                tls_version = ssl.PROTOCOL_TLS
        context = ssl.SSLContext(tls_version)
```

**To Reproduce**
Run vermin on the code example, or clone [paho mqtt](https://github.com/eclipse/paho.mqtt.python) and run it on the master branch.

**Expected behavior**
Minimum version 3.4.

**Environment (please complete the following information):**
- Vermin 0.6.1
- Python 3.7.4

**Other comments**
Excellent tool, thank you for creating it and keep up the good work! :clap:

**Comment by netromdk** [comment]
Thanks :)

The things is, what Vermin does is parsing the python code into an abstract syntax tree (AST) and then traversing it for analysis. It does not evaluate anything since it could have unexpected side-effects. Thus when it reaches the `if` statement it continues to its body and finds a reference to `ssl.PROTOCOL_TLS`, which requires (2.7, 3.6), but it cannot know whether or not the path will be evaluated at runtime.

I have thought about maybe making a lax mode where all conditionals and related (`if`, `while`, `for`, `when`, `try/catch` etc.) will be ignored or won't be traversed but that wouldn't be a perfect solution either.

If you have any ideas, I'm all ears.

**Comment by netromdk** [comment]
But in this case it would work:
```
2.7, 3.2     /tmp/ssl.py
  L1 C7: 'ssl' requires (2.6, 3.0)
  L7: 'ssl.SSLContext' requires (2.7, 3.2)

Minimum required versions: 2.7, 3.2
```

**Comment by vikahl** [comment]
I do not have a solution for the problem and understand the problem with AST and evaluating.

The lax mode sounds like a good option and I think it can help more cases that just my example.

**Comment by netromdk** [comment]
@vikahl Just wanted to say that I've implemented optional [exclusion of symbols](https://github.com/netromdk/vermin#analysis-exclusions) via `--exclude`. Thus if only a few places have to be excluded, maybe the lax mode isn't necessary in some cases.
```
  [--exclude <name>] ...
        Exclude full names, like 'email.parser.FeedParser', from analysis. Useful to
        ignore conditional logic that can trigger incompatible results. It's more fine
        grained than lax mode.

        Examples:
          Exclude 'foo.bar.baz' module/member: --exclude 'foo.bar.baz'
          Exclude 'foo' kwarg:                 --exclude 'somemodule.func(foo)'
          Exclude 'bar' codecs error handler:  --exclude 'ceh=bar'
          Exclude 'baz' codecs encoding:       --exclude 'ce=baz'

  [--exclude-file <file name>] ...
        Exclude full names like --exclude but from a specified file instead. Each line
        constitues an exclusion with the same format as with --exclude.
```

**Comment by vikahl** [comment]
That's actually perfect, great work with the new flags!

**Comment by netromdk** [comment]
Okay, one more way to exclude, @vikahl  😛
As mentioned in the [Analysis Exclusions](https://github.com/netromdk/vermin#analysis-exclusions) section:
```py
import ssl
tls_version = ssl.PROTOCOL_TLSv1
if hasattr(ssl, "PROTOCOL_TLS"):  # novermin
  tls_version = ssl.PROTOCOL_TLS
```
