### ISSUE TITLE
python 3.9 feature not detected: argparse.BooleanOptionalAction

### ISSUE THREAD

**Issue by ollieparanoid** [netromdk/vermin#168]
**Describe the bug**
`argparse.BooleanOptionalAction` is a Python 3.9 feature, but vermin doesn't detect it.

**To Reproduce**

Example code:

```python3
#!/usr/bin/env python3
ret = subparser.add_parser("qemu")
ret.add_argument("--efi", action=argparse.BooleanOptionalAction, help="...")
```
Running `vermin -t=3.7-` on it doesn't report that `argparse.BooleanOptionalAction` is only available in Python >=3.9.

See https://docs.python.org/3/library/argparse.html.

**Expected behavior**
Report that `argparse.BooleanOptionalAction` is only available in Python >=3.9.

**Environment (please complete the following information):**
vermin version: 1.5.1

**Comment by netromdk** [comment]
Thanks for reporting this.

I already have the rule in place for `argparse.BooleanOptionalAction`.
But I actually found an error in the visitation of the AST where keyword values wouldn't be traversed correctly!

By fixing that, it reports the following for your input file (`-vvv -t=3.7-`):
```
!2, 3.9      /tmp/test.py
  L3: 'argparse.BooleanOptionalAction' member requires !2, 3.9

Minimum required versions: 3.9
Incompatible versions:     2
Target versions not met:   3.7-
```
