### ISSUE TITLE
Type annotations available in python 3.4

### ISSUE THREAD

**Issue by csernazs** [netromdk/vermin#17]
**Describe the bug**
I have a project which runs fine on python 3.4 and it uses type annotations. There are two reasons vermin says that my code requires python 3.5: 
- the typing package is missing (which can be installed from a backport but detecting it is out of scope of vermin), this is correct
- for annotations it prints `annotations require 3.5`: this is not correct in my opinion as my code runs fine with python 3.4 and AFAIK type annotations for function definitions were added in the very early version of python 3 (python 3.0 maybe?)

**To Reproduce**
Run vermin on the master branch of https://github.com/csernazs/pytest-httpserver.

**Expected behavior**
Annotations were added in an earlier python version so that would be checked instead, not 3.5.

**Environment (please complete the following information):**
 - I installed the latest version of vermin from pypi

**Comment by netromdk** [comment]
Thanks for noticing. Function annotations were added in 3.0 (https://www.python.org/dev/peps/pep-3107/) and variable annotations in 3.6 (https://www.python.org/dev/peps/pep-0526/). I messed that up.. Will look into this.

**Comment by kissgyorgy** [comment]
Also, the first case could be shown with a comment by "3.4+ with testing installed". But maybe not the scope of vermin.

**Comment by netromdk** [comment]
It has been fixed now, @csernazs .

@kissgyorgy I feel that's outside the scope of this project, though.
