### ISSUE TITLE
Vermin reporting `type` function for Python <2.2

### ISSUE THREAD

**Issue by LukeSavefrogs** [netromdk/vermin#171]
Hi @netromdk.
I start by saying that this tool is amazing and really helps.

However i didn't understand this error i keep getting from Vermin...

## Description
Sadly, at work I need to target Python (actually it's Jython) version 2.1...

`vermin` reports that `'type' member requires 2.2` while it is present in [Python 2.1](https://docs.python.org/release/2.1.1/lib/built-in-funcs.html#built-in-funcs:~:text=2%2C%203\).-,type(object),-Return%20the%20type):
```
2.2, 3.0     D:\Progetti\python2-json\json.py
  print(expr) requires 2.0, 3.0
  L45 C20: 'type' member requires 2.2, 3.0
  L75: Ignoring member 'obj' because it's user-defined!
```

**Environment:**
- Vermin: `v1.5.1`
- OS: Windows 10

### Configuration file
```ini
# It contains all config options with default values commented out.
# The file is typically renamed as "vermin.ini" when copied into a project.

[vermin]
### Verbosity ###
# Verbosity level 1 to 4. -v, -vv, -vvv, and -vvvv shows increasingly more information. Turned off
# at level 0.
#
verbose = 1


### Matching target versions ###
targets = 2.1
                3.0

### Tips ###
show_tips = yes

### Format ###
format = default

### Parse comments ###
parse_comments = no
```

**Comment by netromdk** [comment]
That's great to hear and thanks for the feedback.

I see it's actually present already in [version 2.0](https://docs.python.org/release/2.0/lib/built-in-funcs.html#built-in-funcs).

I'm gonna make a fix for that now.

**Comment by netromdk** [comment]
There we go. Thanks again!

**Comment by LukeSavefrogs** [comment]
Such a quick response!!

Thank you so much @netromdk 😍

**Comment by netromdk** [comment]
You are very welcome! I have a few other fixes in the pipeline but I'm trying to get it in the next few days.

**Comment by LukeSavefrogs** [comment]
> Refer

Great to hear!

I'll gladly wait for it 😁
