### ISSUE TITLE
RFE: ignore hidden directories

### ISSUE THREAD

**Issue by mgedmin** [netromdk/vermin#18]
**Is your feature request related to a problem? Please describe.**

I heard about vermin, decided to check it out, and ran `pipx run vermin ~/projects/check-python-versions`.  Then I saw it complain about files inside `.tox/`

```
File with incompatible versions: /home/mg/projects/check-python-versions/.tox/coverage/lib/python3.6/site-packages/coverage/backward.py
```

**Describe the solution you'd like**

It would be nice (and much faster!) if the directory crawler part of vermin ignored hidden directories such as `.git` and `.tox`.

**Comment by netromdk** [comment]
Thanks. When files have incompatible versions it's not an error, per se. But I do like the idea of ignoring "hidden" folders and files starting with "." by default. Then an optional app argument, `--hidden`, could be used to analyze them anyway.

**Comment by netromdk** [comment]
There we go, @mgedmin .
