### ISSUE TITLE
False positive when using backported zoneinfo

### ISSUE THREAD

**Issue by WhyNotHugo** [netromdk/vermin#189]
**Describe the bug**

I'm trying to use `vermin` on a project that uses `zoneinfo`. The project is properly set up to install the backport on Python < 3.9.

However, vermin reports this as a violation, and won't take `--backport zoneinfo`.

**To Reproduce**

```sh
git clone https://github.com/WhyNotHugo/django-afip.git
cd django-afip
vermin --no-tips --target=3.7 --violations .
vermin --no-tips --target=3.7 --violations --backport zoneinfo .
```

**Expected behavior**

The latter should work.

**Environment (please complete the following information):**

```con
> vermin --version
1.5.1
 
> git --version   
git version 2.40.1
````

**Additional context**

-

**Comment by netromdk** [comment]
Hi @WhyNotHugo. I have not added support for the `zoneinfo` backport yet so writing `--backport zoneinfo` doesn't do anything except yield the error:
```
% vermin --backport zoneinfo
Unknown backport: zoneinfo
Get the full list of backports via `--help`.
```

I'm assuming [this is the backport](https://pypi.org/project/backports.zoneinfo/) you are referring to?
If so then I will add the backport.

**Comment by netromdk** [comment]
There we go:

```
% ./vermin.py --no-tips --target=3.7 --violations ../django-afip
Detecting python files..
Analyzing 61 files using 10 processes..
!2, 3.9      /Users/netrom/git/django-afip/django_afip/clients.py
  'zoneinfo' module requires !2, 3.9

Minimum required versions: 3.9
Incompatible versions:     2
Target versions not met:   3.7

% ./vermin.py --no-tips --target=3.7 --violations --backport zoneinfo ../django-afip
Detecting python files..
Analyzing 61 files using 10 processes..
Minimum required versions: 3.7
Incompatible versions:     2
```

**Comment by WhyNotHugo** [comment]
Many thanks! This was the only quirk blocking me from setting up vermin in a few pipelines :)
