### ISSUE TITLE
"Could not determine minimum required versions!" <= is this really true?

### ISSUE THREAD

**Issue by hwine** [netromdk/vermin#19]
**Describe the bug**
When `vermin` does not believe it determine minimum versions, the output is confusing and hard to interpret.

**To Reproduce**
```
$ vermin -v vermin/__init__.py vermin/printing.py
Detecting python files..
Analyzing 2 files using 4 processes..
             /c/Users/hwine/Desktop/wsl_test/vermin/vermin/__init__.py
2.0, 3.0     /c/Users/hwine/Desktop/wsl_test/vermin/vermin/printing.py
Minimum required versions: 2.0, 3.0
```
and
```
$ vermin -vvv vermin/__init__.py
Detecting python files..
Analyzing using 4 processes..
             /c/Users/hwine/Desktop/wsl_test/vermin/vermin/__init__.py
Could not determine minimum required versions!
```
**Expected behavior**
I can't discern the difference between the reports for the two files above. When I examine the files, I can not see any significant difference. I.e. why is one "2.0, 3.0" and the other "Could not determine...".

That ambiguity makes the output harder to interpret. And harder to convince a coworker of the value. Which combines to make the tool seem less predictable. 😿 

**Environment (please complete the following information):**
```
$ vermin
Vermin 0.6.2
```

**Additional context**

Here's my use case: As a developer working on porting *lots* of legacy scripts and modules from py2 to py3, I want to know where to focus my effort.

With a slight change to the output, I think I'd have something I could not only explain easier to colleagues, but also drive a nice dashboard:
```
$ vermin -v vermin/__init__.py vermin/printing.py
Detecting python files..
Analyzing 2 files using 4 processes..
2    3       /c/Users/hwine/Desktop/wsl_test/vermin/vermin/__init__.py
2.0, 3.0     /c/Users/hwine/Desktop/wsl_test/vermin/vermin/printing.py
Minimum required versions: 2.0, 3.0
```
Where ``2`` & ``3`` means "vermin sees no reason this won't work in that version".

The value of the ``-vvv`` line/function output is tremendous in a large migration. But I need to be able to sell the outer layer as well.

I understand these are "sugar coating", and may not fit your vision. Would there be any objection to finessing the output as above behind a ``--pretty`` flag? I could take a run at a PR for that.

**Comment by netromdk** [comment]
I definitely want the output to be more readable and less confusing. What actually happens is that no rules are triggered with "vermin/vermin/___init__.py" but in "vermin/vermin/printing.py" it hits this one:
```py
if self.printv3():
  mins = combine_versions(mins, (2.0, 3.0))
```
Which means it is using `print(exp)` (v2 and v3) and not `print exp` (v2).

I could add a `-vv` message about that:
> print(expr) requires 2+ or 3+

I like the idea of showing something instead of nothing in the case that it hits no rules.
In addition to that, if not using any verbosity, and no rules are triggered, it should show a different text than:
> Could not determine minimum required versions!

It sounds so intense and looks like an error. What about this?
> No rules were triggered. Cannot guarantee minimum version requirements.
> Might work with 2+ and 3+.

**Comment by netromdk** [comment]
So with the new improvements it could look like this:
```
% ./vermin.py -v vermin/__init__.py
Detecting python files..
Analyzing using 8 processes..
~2, ~3       /Users/netrom/git/vermin/vermin/__init__.py
No rules were triggered. Cannot guarantee minimum version requirements.
Might work with 2+ and/or 3+.
```

**Comment by hwine** [comment]
I prefer ``~2`` to ``-2``, as the later could be read as "not 2".

As for the final output, "might work" sounds imprecise. Maybe something like:
```
No known reason it will not work with 2+ and 3+. Please report if it does not.
```
And add the bug filing info to the usage text. (Or put here, but that might be too much output.)

Thanks for the fast response!

**Comment by netromdk** [comment]
I am using `~2` and `~3` already?  `!2` or `!3` is already used if that version doesn't support a given feature.

Hm yeah, I will change the wording somewhat. Good idea wrt. reporting: can just add the "https://github.com/netromdk/vermin/issues/" at the end of the line.

**Comment by netromdk** [comment]
Thanks for the feedback, @hwine :)
