### ISSUE TITLE
Curious about security notes in v1.5.2 release notes

### ISSUE THREAD

**Issue by ollieparanoid** [netromdk/vermin#203]
Hi,

From the [release notes](https://github.com/netromdk/vermin/releases/tag/v1.5.2):

> Security
> * Upgrade certifi to 2022.12.07 (https://github.com/netromdk/vermin/pull/135, https://github.com/advisories/GHSA-43fp-rhv2-5gv8)
> * Update GitPython to 3.1.30 (https://github.com/netromdk/vermin/pull/157, https://github.com/advisories/GHSA-hcpj-qp55-gfph)

At first glance, this seemed to fix security issues in bundled dependencies. But looking closer at it, I wonder where/if certifi and GitPython get used. From a quick "git grep" it seems like certifi might get used in tests and GitPython... not at all?

So do these actually get used, and are these security updates relevant to users of vermin at all?

If it's not relevant to users, how about writing that clearly in the next release notes?

Thank you very much!

**Comment by netromdk** [comment]
Thank you for the feedback!

Vermin is vanilla Python. All dependencies are only used for linting, analysis, and testing purposes. I should be more clear about this in the release notes!

Much appreciated.

**Comment by netromdk** [comment]
I've updated the [release notes](https://github.com/netromdk/vermin/releases/tag/v1.5.2).

Thanks again!
