### ISSUE TITLE
Vermin Cannot Detect `yield from`

### ISSUE THREAD

**Issue by ozturkberkay** [netromdk/vermin#21]
**Describe the bug**
It seems like vermin cannot detect `yield from` expression, which [introduced in Python 3.3 (PEP 380)](https://docs.python.org/3/whatsnew/3.3.html#pep-380).

**To Reproduce**
Just run vermin -vvv on a Python code which includes the `yield from` expression.

**Expected behavior**
`LX CX: 'yield from' expression requires v3.3+`

**Environment (please complete the following information):**
 - Vermin 0.7.0

**Comment by netromdk** [comment]
Thanks for reporting this, @ozturkberkay ! :) Vermin now detects `yield from` expressions.
