### ISSUE TITLE
Vermin Cannot Detect Dict Comprehensions

### ISSUE THREAD

**Issue by ozturkberkay** [netromdk/vermin#22]
**Describe the bug**

Vermin cannot detect dictionary comprehensions, which were [introduced with 2.7 and 3.0 (PEP 274)](https://www.python.org/dev/peps/pep-0274/).

Before PEP 274:
```python
dict([(key, value) for list_dict in list_of_dicts for key, value in list_dict.items()])
```
After PEP 274:
```python
{key: value for list_dict in list_of_dicts for key, value in list_dict.items()}
```

**To Reproduce**
Just run ```vermin -vvv``` on a Python code which includes a dict comprehension.

**Expected behavior**
```LX CX: Dict comprehension requires (2.7, 3.0)```

**Environment (please complete the following information):**
 - Vermin 0.7.0

**Comment by netromdk** [comment]
Thanks @ozturkberkay . Will get right on it.
