### ISSUE TITLE
<help> sample vermin.ini file 

### ISSUE THREAD

**Issue by mkarthiatgithub** [netromdk/vermin#220]
**Describe the bug**
Looking for simple vermin.ini to target all files above python version 3 and less than 3.11. 
How to specifiy that it needs to look for anything less than 3.11 and above 3

docs is not so clear how to specify twice , why its complaining about version 2 ? 

**To Reproduce**
Steps to reproduce the behavior.
[vermin]
targets = 3
  3,11-
  

It shows 
Minimum required versions: 3.6
Incompatible versions:     2
Target versions not met:   3.0, 3.11-

**Expected behavior**
Simply pass with $? 0 

**Environment (please complete the following information):**
 - Vermin version or Git commit [e.g. 0.4.0]

**Additional context**

**Comment by mkarthiatgithub** [comment]
vermin --version
1.5.2
Mac

**Comment by netromdk** [comment]
Hi there.

In this case you should only define one target:
```
[vermin]
targets = 3.11-
```

This means minimum version 3.0 to, and including, 3.11.

It is saying that it is incompatible with version 2.x because you have code that doesn't function on it. If you use `-v..` then you can see why.

**Comment by mkarthiatgithub** [comment]
Thanks. 
I do not want it to report for Python version 2, as my program will never run on that version. 
How do I stop reporting for Version 2 ?

**Comment by netromdk** [comment]
You cannot. It isn't doing anything else than telling you this information.

**Comment by mkarthiatgithub** [comment]
thank you !  I will close this issue.

**Comment by netromdk** [comment]
You are very welcome. Thanks.
