### ISSUE TITLE
How to run on program without .py extension, and how to see usage message?

### ISSUE THREAD

**Issue by bulletmark** [netromdk/vermin#23]
My issues are best explained by looking at each of the commands I execute below and their output:
```
pc:~/my-prog ls -l
total 4
-rwxr-xr-x 1 mark mark 51 Oct 16 12:53 my-prog

pc:~/my-prog cat my-prog 
#!/usr/bin/env python3
print('This is my program')

pc:~/my-prog ../env/bin/vermin my-prog 
Detecting python files..
No files specified to analyze!

pc:~/my-prog ../env/bin/vermin ./my-prog 
Detecting python files..
No files specified to analyze!

pc:~/my-prog ../env/bin/vermin .
Detecting python files..
No files specified to analyze!

pc:~/my-prog ../env/bin/vermin -h
Detecting python files..
No files specified to analyze!

pc:~/my-prog ../env/bin/vermin --help
Detecting python files..
No files specified to analyze!

pc:~/my-prog ../env/bin/vermin --version
Detecting python files..
No files specified to analyze!

pc:~/my-prog ../env/bin/vermin -v
Detecting python files..
No files specified to analyze!

pc:~/my-prog ../env/bin/pip list 
Package    Version
---------- -------
pip        19.3   
setuptools 40.8.0 
vermin     0.8.0  
```
So the issues I am asking about are:

1. How can I run `vermin` on a python program without a .py extension?
2. There seems to be no usage message? Nor a way to check the version?
3. Also, I originally installed that `env/` virtualenv dir within the source folder (like users normally do for a project) but there seems to be no way to stop vermin recursing through that dir?

**Comment by netromdk** [comment]
> 1. How can I run vermin on a python program without a .py extension?

Currently it will only scan .py and .pyw files. Any reason not to put an extension? If it scanned all files without extensions, it would be a lot slower and a lot of parse errors would be printed to the shell.

> 2. There seems to be no usage message? Nor a way to check the version?

It prints the usage when using no arguments. But I have thought about adding `-h` and `--help` for this purpose as well. The version is printed at the top of the usage/help info.

> 3. Also, I originally installed that env/ virtualenv dir within the source folder [..]

It will, by default, ignore all files and folders starting with "." because those are "hidden" on *nix systems (using `--hidden` will scan them anyway). If it's not starting with "." then it cannot know if it shouldn't scan it. You can always tell it to scan a subset of folders, like:
```
% ./vermin.py vermin tests
Detecting python files..
Analyzing 35 files using 8 processes..
Minimum required versions: 3.0
Incompatible versions:     2
```

**Comment by bulletmark** [comment]
I put `.py` extensions on modules (obviously) but I (and very many others) never put any extension on a program/utility which is intended to be run directly. Users don't care what language a program is written in. Adding `.py` in that case is ugly and awkward to type.

Possibly _vermin_ should use a heuristic to determine what are the python files? At least they should be able to be explicitly specified which is something that does not currently appear to be possible.

It's a python program so I am very surprised you don't use `argparse` which gives you `-h/--help` functionality automatically.

The `env` problem would go away if there was some way of explicitly specifying what files/dirs to look at, and/or what files/dirs to exclude.

**Comment by bulletmark** [comment]
Surely you can agree with me that the following should be fixed, where my-prog is a simple single python source file.
```
$ vermin my-prog 
Detecting python files..
No files specified to analyze!
```

**Comment by netromdk** [comment]
A heuristic could be implemented. Can look into that. Ugliness is a subjective thing.

As is clearly stated in the README:
> [..] Additionally, since the code is vanilla Python, and it doesn't have any external dependencies, it works with v2.7+ and v3+.

And `argparse` requires 2.7+ and 3.2+, and thus not 3.0 and 3.1.

I have definitely thought about adding a way to exclude files and folders.

**Comment by netromdk** [comment]
> Surely you can agree with me that the following should be fixed, where my-prog is a simple single python source file?

Yes, you are right that it isn't very user-friendly. :)

**Comment by netromdk** [comment]
Now it will analyze your file:
```
% ./vermin.py -v my-prog
Detecting python files..
Analyzing using 8 processes..
2.0, 3.0     /Users/netrom/git/vermin/my-prog
Minimum required versions: 2.0, 3.0
```

**Comment by bulletmark** [comment]
Thanks for that. Works much better.

Ran it as a test on my program and [found a bug](https://github.com/bulletmark/libinput-gestures/commit/d7fa0547a787e92c4552eacc87d0061411daae8c) immediately!

**Comment by bulletmark** [comment]
Just another question - when you do think you will package up a new version with this change for PyPI?

This utility is so useful I think I will create an Arch Linux AUR package for it but best to source releases from PyPI.

**Comment by netromdk** [comment]
I'm happy it spotted something in your project!

Version 0.8.1 has been released just now and uploaded to PyPi.
Sounds great. If you do then I'd like to link to it in my README here.

**Comment by bulletmark** [comment]
Already added: https://aur.archlinux.org/packages/vermin/. Arch Linux users can install simply by typing `yay -S vermin`. You can add that, or I will submit a PR to you?

**Comment by netromdk** [comment]
Cool. Sure, you can add a PR 😊

**Comment by bulletmark** [comment]
The `-i` switch does not seem to work?
```
pc:~/Data/src/libinput-gestures vermin -i -q libinput-gestures
Minimum required versions: 3.4
Incompatible versions:     2
```

**Comment by netromdk** [comment]
What it does is not printing out when files are incompatible. Like:
```
% ./vermin.py examples
Detecting python files..
Analyzing 47 files using 8 processes..
File with incompatible versions: /Users/netrom/git/vermin/examples/dict.py
File with incompatible versions: /Users/netrom/git/vermin/examples/kwargs.py
File with incompatible versions: /Users/netrom/git/vermin/examples/longv2.py
Note: Some files had incompatible versions so the results might not be correct!
Minimum required versions: 3.8
Incompatible versions:     2
```

vs:
```
% ./vermin.py -i examples
Detecting python files..
Analyzing 47 files using 8 processes..
Incompatible versions:     2, 3
```

Hm, but could you try running it with `-v` and not `-q` to get more info?

**Comment by bulletmark** [comment]
As far as I am concerned, Python 2 is irrelevant nowadays. So I just want the minimum absolute compatible version printed. Is there no way to just output that?

**Comment by netromdk** [comment]
Hm, no it prints everything it finds out. But I don't see the problem? It says that you require 3.4 and that 2.x doesn't support your code.

**Comment by bulletmark** [comment]
It's just extra noise that I don't care about and would prefer not to see.

**Comment by netromdk** [comment]
I just scanned your file to test. It's because you only scan one file, then `-i` doesn't make sense since it's the workings between files.

Anyway, I could add something to state that 2.x results should be ignored. Will give it some thought.

**Comment by bulletmark** [comment]
But a user who specifies `-i` is saying he does not want to see incompatible versions messages, so why output that summary line?

**Comment by netromdk** [comment]
That's a very good point :p
I will make the addition sometime today.

**Comment by bulletmark** [comment]
Reopening this bug because I just discovered the fix does not do what I expect.
```
pc:~ cat tmp
print('this is a vermin test')
pc:~ vermin -v tmp
Detecting python files..
No files specified to analyze!
```
Hard specifying a file on the command line should mean `vermin` does no go looking for a shebang etc.

**Comment by netromdk** [comment]
Yes, that is a good point. Now it will always attempt parsing of directly specified files (when not transitively detected):
```
% ./vermin.py -v tmp
Detecting python files..
Analyzing using 8 processes..
2.0, 3.0     /Users/netrom/git/vermin/tmp
Minimum required versions: 2.0, 3.0
```

**Comment by bulletmark** [comment]
Sorry, but why does that "Detecting python files.." line get printed in this case?

Regardless, I personally think that line and the next one should be completely removed.  Users don't care about implementation details, they just want to see the results.

**Comment by netromdk** [comment]
It gets shown because searching any number of possible folder structures can take time which is unknown before initiating the search. After the search is complete the concurrent analysis commences.

I guess it might be a verbose level one detail.
