### ISSUE TITLE
Publish sdist onto pypi?

### ISSUE THREAD

**Issue by chenrui333** [netromdk/vermin#243]
👋 looks like right now there is no sdist on pypi, any chance of publishing the source tarball? Thanks!

**Comment by netromdk** [comment]
Hi there. I've just released version 1.6.0: https://github.com/netromdk/vermin/releases/tag/v1.6.0
And I've included an sdist in addition to the bdist: https://pypi.org/project/vermin/1.6.0/#files
Thanks for the suggestion.
