### ISSUE TITLE
Target version check should also be successful if the version is newer

### ISSUE THREAD

**Issue by samuelb** [netromdk/vermin#26]
**Is your feature request related to a problem? Please describe.**
vermin supports the parameter `-t` to specify target python version the project of file should support. This check is successful only if the target version is exactly the same as the determined minimum required version.

Example with vermin version 0.8.1:
```
% cat test.py
print(f"This is a f-string. {__name__}")

% vermin -q -t=3.6 test.py
Minimum required versions: 3.6
Incompatible versions:     2
# exit code: 0

% vermin -q -t=3.7 test.py
Minimum required versions: 3.6
Incompatible versions:     2
Target versions not met:   3.7
# exit code: 1
```
You can see in the last execution that vermin target version check is unsuccessful even so the test code would be also be perfectly compatible with Python version 3.7 too. 

**Describe the solution you'd like**
I want that the vermin target version check is successful if the target version is fulfilled and if the target version is newer as the determined one. 

**Describe alternatives you've considered**
Well, I could get the determined minimum version from the vermin output and build my condition myself somehow. While this would be fine when vermin is used within a test suite, it not a good option when using vermin a cli utility directly.

**Comment by netromdk** [comment]
Thanks for the feedback. I see your point but in some cases you don't want it to match if the minimum required version changes. Imagine a project that needs to stay at a certain minimum version.

However, I'm thinking about extending the syntax to allow for `-t>=V` as well. Then you can do `-t=3.6` for matching exactly 3.6, and `-t>=3.6` for 3.6+.

**Comment by netromdk** [comment]
Ah, no, can't use `-t>=3.6` since it'll redirect to "=3.6" on CLI. But the syntax could also be `-t=3.6+` for matching 3.6 or above.

**Comment by netromdk** [comment]
But on further reflection, it makes more sense to use `-t=V-`. Now your use case above yields the expected outcome since 3.6 <= 3.7 (hence the "-"):
```sh
% ./vermin.py -t=3.7- /tmp/test.py ; echo $?
Minimum required versions: 3.6
Incompatible versions:     2
0
```

**Comment by samuelb** [comment]
That's awesome! Thank you 👍
