### ISSUE TITLE
Missing Python 3.7 features, incorrectly reports as 3.5-compatible

### ISSUE THREAD

**Issue by a-tinsmith** [netromdk/vermin#33]
**Describe the bug**
When testing Python code that uses features from v3.7 the script incorrectly reports minimal version as 3.5

**To Reproduce**

1. Create a file with this contents:
```python
#!/usr/bin/env python3

import subprocess

proc = subprocess.run('ls -l -a',
                      shell=True,
#                      universal_newlines=True,
                      text=True,    # available since 3.7+
                      stderr=subprocess.STDOUT,
                      stdout=subprocess.PIPE)
proc.check_returncode()
print(proc.stdout)
```
2. Execute
`vermin -vvvv bug.py`

**Expected behavior**
The script detects that `text` parameter is available in Python 3.7+

**Actual behavior**
```
Detecting python files..
Analyzing using 12 processes..
!2, 3.5      /Users/user/src/other/vermin_bug/subprocess_bug.py
  L3 C7: 'subprocess' requires 2.4, 3.0
  L5: 'subprocess.run' requires !2, 3.5
  L5: True/False constant requires v2.2+.
  print(expr) requires 2+ or 3+

Minimum required versions: 3.5
Incompatible versions:     2
```

**Environment (please complete the following information):**
 - Vermin version: 0.9.1

**Comment by netromdk** [comment]
Thank you for reporting the bug. It has been fixed and will now yield the following instead:
```
% ./vermin.py -vv /tmp/bug.py
Detecting python files..
Analyzing using 8 processes..
!2, 3.7      /tmp/bug.py
  'subprocess' requires 2.4, 3.0
  'subprocess.run' requires !2, 3.5
  'subprocess.run(text)' requires !2, 3.7
  print(expr) requires 2+ or 3+

Minimum required versions: 3.7
Incompatible versions:     2
```

I will add the rest of the missing rules from the `subprocess` module to the `dev` branch soon and then merge that to `master`.

**Comment by a-tinsmith** [comment]
Thanks for the prompt response and fix. `verrmin` is awesome!

**Comment by netromdk** [comment]
Thanks! You're very welcome.

**Comment by netromdk** [comment]
[v0.9.2](https://github.com/netromdk/vermin/releases/tag/v0.9.2) has been released and uploaded to [PyPi](https://pypi.python.org/pypi/vermin/).
