### ISSUE TITLE
False positives when detecting generalized unpacking and bytes formatting

### ISSUE THREAD

**Issue by gousaiyang** [netromdk/vermin#38]
When I try the latest version of vermin (from the master branch, with recent implemenation of generalized unpacking and bytes formatting detection) against some code of my projects, I noticed some false positives when detecting generalized unpacking and bytes formatting.

**Case 1:**

```
d = {'a': 'b'}
dict(**d)
```

Expected:  No issues detected (`Minimum required versions: ~2, ~3`)

Actual: `L2: generalized unpacking requires 3.5+`

**Case 2:**

```
'%x' % 66
```

Expected:  No issues detected (`Minimum required versions: ~2, ~3`)

Actual: ``L1: bytes `%` formatting requires 3.5+ (or 2.6+ as `str` synonym)``

In [this commit](https://github.com/netromdk/vermin/commit/04444349a4f006d9b24077e1eeedf648d28cc908#diff-060b71b621fc29fbdf95977b0f00aef0R904), why is `isinstance(node.left, ast.Str)` necessary? Is it because of some compatibility reasons? `b''` is 2.6+, but `'%x' % 66` is `~2, ~3`.

**Comment by netromdk** [comment]
Thanks for noticing! :) Fixing those things. Yeah, it was related to being compatible but I will do it in another way that's more clear.

**Comment by gousaiyang** [comment]
Here are some test results under Python 3.4. Invalid cases should be regarded as generalized unpacking (they are valid on 3.5+) but valid cases are not.

Unpacking in literals (tuple, list, set, and dictionary displays) is always invalid in Python 3.4:
`(*(1,),)` -> invalid
`(*(1, 2),)` -> invalid
`(0, *(1, 2))` -> invalid
`(*(1, 2), 3)` -> invalid
`(0, *(1, 2), 3)` -> invalid
`(*(1, 2), *(3, 4))` -> invalid
`[*[1]]` -> invalid
`[*[1, 2]]` -> invalid
`[0, *[1, 2]]` -> invalid
`[*[1, 2], 3]` -> invalid
`[0, *[1, 2], 3]` -> invalid
`[*[1, 2], *[3, 4]]` -> invalid
`{*{1}}` -> invalid
`{*{1, 2}}` -> invalid
`{0, *{1, 2}}` -> invalid
`{*{1, 2}, 3}` -> invalid
`{0, *{1, 2}, 3}` -> invalid
`{*{1, 2}, *{3, 4}}` -> invalid
`{**{1: 1}}` -> invalid
`{**{1: 1, 2: 2}}` -> invalid
`{0: 0, **{1: 1, 2: 2}}` -> invalid
`{**{1: 1, 2: 2}, 3: 3}` -> invalid
`{0: 0, **{1: 1, 2: 2}, 3: 3}` -> invalid
`{**{1: 1, 2: 2}, **{3: 3, 4: 4}}` -> invalid

In Python 3.4, unpacking in function call parameter list is only allowed at the end of the parameter list, and only one unpacking is allowed:
`print(*(1,))` -> valid
`print(*(1, 2))` -> valid
`print(0, *(1, 2))` -> valid
`print(*(1, 2), 3)` -> invalid
`print(0, *(1, 2), 3)` -> invalid
`print(*(1, 2), *(3, 4))` -> invalid
`dict(**{"b": 1})` -> valid
`dict(**{"b": 1, "c": 2})` -> valid
`dict(a=0, **{"b": 1, "c": 2})` -> valid
`dict(**{"b": 1, "c": 2}, d=3)` -> invalid
`dict(a=0, **{"b": 1, "c": 2}, d=3)` -> invalid
`dict(**{"b": 1, "c": 2}, **{"d": 3, "e": 4})` -> invalid

**Comment by netromdk** [comment]
Thanks! Will look it through.

**Comment by netromdk** [comment]
@gousaiyang we agree it's fixed now? :)

**Comment by gousaiyang** [comment]
Looks good. It is fine to close this issue now.
