### ISSUE TITLE
Please change Arch AUR name to python-vermin

### ISSUE THREAD

**Issue by bulletmark** [netromdk/vermin#41]
Sorry, you sent me a message about this but I first deleted my repo clone and thus could not reply to you(!)

I have changed the name of the Arch AUR package from vermin to python-vermin because that is more consistent with the Arch naming scheme. I had prepared a PR long ago for this but the Arch devs took ages to approve it and by the time they did I had forgotten about my PR (and it was out of date). So yes, please change `yay -S vermin` to `yay -S python-vermin` in the README here.

**Comment by netromdk** [comment]
Thanks and no worries. :)
