### ISSUE TITLE
Make #novermin comments work better with other linter comments

### ISSUE THREAD

**Issue by gousaiyang** [netromdk/vermin#43]
Sometimes we need to use multiple linter comments in one line (see also https://github.com/PyCQA/pylint/issues/2485). Consider the following code snippet, which has three linter comments in one line:

```python
import os

if hasattr(os, 'sched_getaffinity'):
    CPU_CNT = len(os.sched_getaffinity(0))  # type: ignore[attr-defined] # pylint: disable=no-member # novermin
else:
    ...
```

It would be good if everything works no matter how these comments are ordered, which is the current behavior of Pylint and Flake8. But for vermin, currently it only works (i.e. correctly exclude the line from analysis) when `# novermin` is the last comment. `# novermin # type: ignore[attr-defined] # pylint: disable=no-member` and `# type: ignore[attr-defined] # novermin # pylint: disable=no-member` do not work (for some reason Mypy requires the type comment to be the first comment, but that's not a vermin problem.)

I see [a relevant change](https://github.com/netromdk/vermin/commit/7a7a84245a50806f6c3b4708067dc1548eafa436) in the master branch. A caveat is that extracting comments with [this regular expression](https://github.com/netromdk/vermin/blob/7a7a84245a50806f6c3b4708067dc1548eafa436/vermin/parser.py#L6) may introduce false positive `# novermin` comments if `# novermin` happens to be in a string literal. Maybe using the [`tokenize`](https://docs.python.org/3/library/tokenize.html) module to detect `COMMENT` tokens is a better way.

**Environment**
 - Vermin version 0.10.3

**Comment by netromdk** [comment]
Thanks, that is an interesting proposal with `tokenize`!

I've thought about this before; mainly that it's a mess when using several solutions relying on comments at the same time. I do think it's a solution if the different "contexts" are defined as `[# comment], ..`

**Comment by netromdk** [comment]
I got it working. And also double-checked with your input case.
