### ISSUE TITLE
Code in name().method(kwargs=...) form not detected

### ISSUE THREAD

**Issue by gousaiyang** [netromdk/vermin#44]
There are three slightly different code snippets, triggering different detection behaviors of vermin:

```python
from zipfile import ZipFile
ZipFile.writestr(compress_type=None)
```

Correct: detected as 2.7+, 3.2+

```python
from zipfile import ZipFile
ZipFile().writestr(compress_type=None)
```

Wrong: detected as ~2, ~3

```python
from zipfile import ZipFile
zf = ZipFile()
zf.writestr(compress_type=None)
```

Correct: detected as 2.7+, 3.2+

However if the rule is not a kwargs rule, this bug does not happen:

```python
from zipfile import ZipFile
ZipFile.setpassword()
```

```python
from zipfile import ZipFile
ZipFile().setpassword()
```

```python
from zipfile import ZipFile
zf = ZipFile()
zf.setpassword()
```

All these three cases are correctly detected as 2.6+, 3.0+.

**Environment**
 - Vermin version 0.10.3

**Comment by netromdk** [comment]
Thanks for letting me know. I will look into it.

**Comment by netromdk** [comment]
Alright, it's fixed :)
