### ISSUE TITLE
Detection for builtin exceptions

### ISSUE THREAD

**Issue by gousaiyang** [netromdk/vermin#45]
With the current detection heuristics in vermin, the use of builtin exceptions cannot be effectively detected, although we already have [a section for builtin exceptions](https://github.com/netromdk/vermin/blob/fca4f9632b27c13976d6579d72e1a73e4849a2e3/vermin/rules.py#L339) in `rules.py`.

Raising exceptions:
`raise ModuleNotFoundError` -> not detected, because `ModuleNotFoundError` is a plain name
`raise ModuleNotFoundError('some message')` -> correctly detected as 3.6+, because there is a function call
`raise shutil.SameFileError` -> correctly detected as 3.4+, because `shutil.SameFileError` is a dotted name (i.e. involves an attribute access)

Catching exceptions:
```python
try:
    import zlib
    import gzip
    gzip.GzipFile
except (ModuleNotFoundError, AttributeError):
    has_gz_support = False
else:
    has_gz_support = True
```

should be detected as 3.6+, but currently not detected.

Maybe we can handle `raise` and `except` statements specially to detected them. It might also be good to pull rules for builtin exceptions out of `MOD_MEM_REQS` (create a new category of rules), if that makes things easier.

**Environment**
 - Vermin version 0.10.3

**Comment by netromdk** [comment]
Thanks. I will fix this.

**Comment by netromdk** [comment]
There we go. Thanks again!
