### ISSUE TITLE
Backports not properly ignored

### ISSUE THREAD

**Issue by adamjstewart** [netromdk/vermin#46]
**Describe the bug**

Even if I add `--backport argparse` to `vermin`, it still reports a minimum version requirement of Python 2.7.

**To Reproduce**

```console
$ cat > foo.py
import argparse
$ vermin --backport argparse -vvvv foo.py
Detecting python files..
Analyzing using 4 processes..
2.7, 3.2     /Users/Adam/Downloads/foo.py
  L1 C7: 'argparse' requires 2.7, 3.2

Minimum required versions: 2.7, 3.2
```

**Expected behavior**

Any version of Python should work for this file.

**Environment**

* Vermin 0.10.4
* macOS 10.15.7
* Python 3.8.5

**Additional information**

If you have any trouble reproducing this, I suspect that this is a macOS + Python 3.8 bug. See https://docs.python.org/3.8/library/multiprocessing.html#contexts-and-start-methods:

> _Changed in version 3.8:_ On macOS, the _spawn_ start method is now the default. The _fork_ start method should be considered unsafe as it can lead to crashes of the subprocess. See [bpo-33725](https://bugs.python.org/issue33725).

One workaround would be to force it to always use the _fork_ start method by replacing `multiprocessing` with `multiprocessing.get_context('fork')` everywhere it's used. We recently had to do this for Spack: https://github.com/spack/spack/pull/18124

A more permanent workaround would be to ensure that both _spawn_ and _fork_ work as expected.

**Comment by netromdk** [comment]
Thanks for reporting this! I will make a fix that uses the fork context.

**Comment by netromdk** [comment]
Using `fork` also fixed it for me. I will look into making it work with `spawn` and what the issue actually is for Vermin in that regard.

**Comment by netromdk** [comment]
Alright, now it also works with `spawn()`. As per the [docs](https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods):
> The parent process starts a fresh python interpreter process. The child process will only inherit those resources necessary to run the process objects `run()` method. In particular, unnecessary file descriptors and handles from the parent process will not be inherited.

So I found that the only state that wasn't inherited was my singleton config instance, but the config is actually already copied and passed to each invocation of `process_individual()` so reestablishing the config singleton in the newly spawned process was easy.

I will publish version 0.10.5 in a few hours. 👍 
Thanks again.

**Comment by netromdk** [comment]
[v0.10.5](https://github.com/netromdk/vermin/releases/tag/v0.10.5) has been released.

**Comment by adamjstewart** [comment]
Thanks for the fast fix! I added 0.10.5 to Spack: https://github.com/spack/spack/pull/19017

Btw, would you have any interest in being listed as a maintainer of `py-vermin` in Spack? You don't need to be a Spack expert, it just gives us someone to ping if a user reports a build error or submits a PR to modify the package.

**Comment by netromdk** [comment]
That sounds great.

Sure, I wouldn't mind helping out though I have to admit I don't know much about the internals of the project. Where will it be listed?

**Comment by adamjstewart** [comment]
Basically, I would add:
```python
maintainers = ['netromdk']
```
to the build recipe. In the future, it will automatically ping you when someone submits a PR that modifies `py-vermin`. We also tell people to run `spack maintainers py-vermin` if they have a build issue with the package, and it will report your GitHub handle.

For Spack installation instructions, it would look like:
```console
$ git clone https://github.com/spack/spack.git
$ . spack/share/spack/setup-env.sh  # depending on shell
$ spack install py-vermin
$ spack load py-vermin
```
There are a lot of other ways you can use Spack, like with Environments or Module files, but this is probably the simplest.

**Comment by netromdk** [comment]
Yup, that's alright with me. :)

Thanks. I'll add something similar to that.

**Comment by adamjstewart** [comment]
Awesome, I added you.

Btw, in the future, if you cut a new release, you can add it to Spack by running:
```console
$ spack checksum py-vermin 0.10.5

==> Fetching https://github.com/netromdk/vermin/archive/v0.10.5.tar.gz
####################################################################################### 100.0% 

    version('0.10.5', sha256='00601356e8e10688c52248ce0acc55d5b45417b462d5aa6887a6b073f0d33e0b')
```
Then run `spack edit py-vermin` and copy-n-paste that line into the package and submit a PR. Of course, I'm also happy to add new versions to the package as well, although I might not add new versions as regularly.

**Comment by netromdk** [comment]
That's real easy. Will be sure to do that the next time around.
