### ISSUE TITLE
vermin doesn't print why it thinks a file has incompatible versions

### ISSUE THREAD

**Issue by CendioOssman** [netromdk/vermin#49]
**Describe the bug**
vermin doesn't print why it thinks a file has incompatible versions making it very difficult to figure out what is wrong with the code.

**To Reproduce**
E.g. this file:

```python
try:
  import socketserver
except ImportError:
  import SocketServer
```

**Expected behavior**
Output similar to the success case, e.g.:

```
$ vermin -p=1 -vvvv ./test.py 
Detecting python files..
Analyzing using 1 processes..
File with incompatible versions: test.py
!2, !3      /local/home/ossman/devel/vermin/test.py
  L2 C9: 'socketserver' requires !2, 3.0
  L4 C9: 'SocketServer' requires 2.0, !3
Note: Some files had incompatible versions so the results might not be correct!
Minimum required versions: ~2, ~3
```

**Environment (please complete the following information):**
 - Vermin commit f5cafde1c6d8e30013f50e3d8cdfbbbaa34f98aa

**Comment by netromdk** [comment]
Thanks, that's actually a good point.. In your case, it's because `socketserver` doesn't work with py2 and `SocketServer` doesn't work with py3, so it's incompatible. I will think about how this could be better communicated.

**Comment by netromdk** [comment]
What about something like the following?
```
% ./vermin.py /tmp/test14.py
File with incompatible versions: /tmp/test14.py
  Incompatible constructs: socketserver (requires !2, 3.0) vs. SocketServer (requires 2.0, !3)
Note: Some files had incompatible versions so the results might not be correct!
Minimum required versions: ~2, ~3
```

**Comment by CendioOssman** [comment]
Looks good. As long as the information is there then I'm not too picky about formatting. :)

**Comment by netromdk** [comment]
Alright, there we go. Thanks again :)
