### ISSUE TITLE
Log version-specific features that raise requirements

### ISSUE THREAD

**Issue by Stevoisiak** [netromdk/vermin#5]
Currently running vermin on a project folder will display the minimum required Python version. However, it doesn't go into any detail for *why* a project requires that version.

```
C:\>vermin U:\Documents\Scripts\wfc_helper
Detecting python files..
Analyzing 13 files using 4 processes..
Minimum required versions: 3.6
Incompatible versions:     2
```

To help users learn *why* a version is required, I propose listing what features a project uses to require a specific version of Python.

```
C:\>vermin U:\Documents\Scripts\wfc_helper
Detecting python files..
Analyzing 13 files using 4 processes..
Minimum required versions: 3.6
Incompatible versions:     2
Features:                  f-strings (3.6)
                           import typing (3.5)
```

Alternatively, if a folder is specified, Vermin could specify which file or line number caused the current requirements.

**Comment by netromdk** [comment]
Thanks for opening the issues, @Stevoisiak.

You can use the verbosity arguments to list that information, you can use `-v`, `-vv`, or `-vvv` for varying levels of detail.

Try seeing if that information is useful enough?

But I like your idea of listing this information. However, it could become a pretty long list which is why I decided on the verbosity arguments.

Thoughts?

**Comment by Stevoisiak** [comment]
@netromdk Thank you. Using `-v` was helpful for determining requirements for individual files in my project. Is this argument mentioned anywhere in the Readme?

While `-v` helps narrow down which file raises the requirements, the user will still need to manually examine the file for version-specific features. This also requires the user to know which features were introduced in each Python version.

**Comment by netromdk** [comment]
It is mentioned although a bit subtle:
> -v..    Verbosity level 1 to 3. -v shows less than -vv but more than no verbosity.

Perhaps it should state something about the information it can show.

With `-vv`, in addition to file names, you can get output such as the following:
```
`"..".format(..)` requires [2.6, 3.0]
'collections' requires (2.4, 3.0)
'collections.defaultdict' requires (2.5, 3.0)
'multiprocessing' requires (2.6, 3.0)
'format' requires (2.6, 3.0)
```

**Comment by netromdk** [comment]
Could I get the files you are using so I can try for myself? Thanks

What do you get with `-vvv`?

**Comment by Stevoisiak** [comment]
@netromdk Unfortunately the project isn't public, so I can't share the files. Using `-vvv` gives a similar output.

```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\svascellar>vermin -vvv U:\Documents\Scripts\wfc_helper
Detecting python files..
Analyzing 13 files using 4 processes..
             U:\Documents\Scripts\wfc_helper\wfc_helper\core\__init__.py
             U:\Documents\Scripts\wfc_helper\wfc_helper\core\wfc_exception.py
             U:\Documents\Scripts\wfc_helper\tests\__init__.py
2.3, 3.0     U:\Documents\Scripts\wfc_helper\tests\test_wfc_connection.py
!2, 3.6      U:\Documents\Scripts\wfc_helper\wfc_helper\gui\logon_frame.py
             U:\Documents\Scripts\wfc_helper\wfc_helper\gui\__init__.py
!2, 3.6      U:\Documents\Scripts\wfc_helper\wfc_helper\core\wfc_connection.py
!2, 3.0      U:\Documents\Scripts\wfc_helper\wfc_helper\gui\wfc_helper_app.py
!2, 3.6      U:\Documents\Scripts\wfc_helper\wfc_helper\gui\add_job_frame.py
2.4, 3.0     U:\Documents\Scripts\wfc_helper\setup.py
             U:\Documents\Scripts\wfc_helper\wfc_helper\core\tags.py
             U:\Documents\Scripts\wfc_helper\wfc_helper\__init__.py
             U:\Documents\Scripts\wfc_helper\wfc_helper\__main__.py
Minimum required versions: 3.6
Incompatible versions:     2

```

**Comment by netromdk** [comment]
That's okay, I understand.

It is very weird that it only responds to `-v` but not further than that.
What version of Python are you using here? 2.7+ or 3.0+ is required.

**Comment by netromdk** [comment]
Thanks. I can see that it is a Windows prompt related issue after I booted up a Windows VM. I'll try to fix that!

**Comment by netromdk** [comment]
@Stevoisiak I've fixed so multiprocessing on Windows doesn't throw away the output information and released v0.4.3. Now you'll be able to see the specific results via `-vv` as intended.

**Comment by Stevoisiak** [comment]
@netromdk Confirmed. `-vv` is working as intended in v0.4.3. This feature does exactly what I was looking for.

```
C:\Users\svascellar>vermin -vv U:\Documents\Scripts\wfc_helper
Detecting python files..
Analyzing 13 files using 4 processes..
             U:\Documents\Scripts\wfc_helper\wfc_helper\__main__.py
!2, 3.6      U:\Documents\Scripts\wfc_helper\wfc_helper\gui\logon_frame.py
  'logging' requires (2.3, 3.0)
  'tkinter' requires (None, 3.0)

2.3, 3.0     U:\Documents\Scripts\wfc_helper\tests\test_wfc_connection.py
  'datetime' requires (2.3, 3.0)
  'unittest' requires (2.1, 3.0)

!2, 3.6      U:\Documents\Scripts\wfc_helper\wfc_helper\gui\add_job_frame.py
  'datetime' requires (2.3, 3.0)
  'logging' requires (2.3, 3.0)
  'tkinter' requires (None, 3.0)

             U:\Documents\Scripts\wfc_helper\wfc_helper\core\tags.py
2.4, 3.0     U:\Documents\Scripts\wfc_helper\setup.py
  'subprocess' requires (2.4, 3.0)

             U:\Documents\Scripts\wfc_helper\wfc_helper\__init__.py
             U:\Documents\Scripts\wfc_helper\wfc_helper\gui\__init__.py
             U:\Documents\Scripts\wfc_helper\wfc_helper\core\__init__.py
             U:\Documents\Scripts\wfc_helper\wfc_helper\core\wfc_exception.py
!2, 3.6      U:\Documents\Scripts\wfc_helper\wfc_helper\core\wfc_connection.py
  'logging' requires (2.3, 3.0)

!2, 3.0      U:\Documents\Scripts\wfc_helper\wfc_helper\gui\wfc_helper_app.py
  'logging' requires (2.3, 3.0)
  'tkinter' requires (None, 3.0)

             U:\Documents\Scripts\wfc_helper\tests\__init__.py
Minimum required versions: 3.6
Incompatible versions:     2
```

**Comment by Stevoisiak** [comment]
@netromdk As a separate issue, I don't see any listing for f-strings requiring 3.6, even when using `-vvv`.

**Comment by netromdk** [comment]
Thanks for the response. Yeah, I was wondering about that as well, looking at your output. I will file an issue for that.

**Comment by netromdk** [comment]
Filed under #6.
Thanks again!
