### ISSUE TITLE
Python API

### ISSUE THREAD

**Issue by gousaiyang** [netromdk/vermin#52]
It would be good if vermin can export a module-level function that accepts a code string and reports its minimum version. This allows programmatic use of vermin in Python without having to invoke the CLI.

In fact, I'm occasionally using [one of your test utility functions](https://github.com/netromdk/vermin/blob/4d5acb7c41ffd80e7cd6d1804a3d5b36a8797e89/tests/testutils.py#L74) to run vermin against short code snippets in IPython without having to create a file to store the code. However this function is in the `tests` package and thus is not accessible from the `vermin` package. Also, this test function only returns the minimum version of the code. Where to report details of each rule matched and other tips (like "You're using potentially backported modules") is a problem.

**Comment by netromdk** [comment]
Hm, I see your point. It just wasn't how the program was envisioned to function. But I can't see any issue with exposing the functionality, though. If added, I think a first version might just be reporting the minimum versions as it would require a slight rewrite to also include other findings.

However, I like the idea and I'll look into it, thanks 👍

**Comment by gousaiyang** [comment]
It's good if the initial version only returns the minimum versions. Detail reporting may be considered in the future.

**Comment by netromdk** [comment]
I've exposed the `detect()` function via the module on a branch: [`expose_api`](https://github.com/netromdk/vermin/tree/expose_api)

Another thing that could be exposed is [`visit()`](https://github.com/netromdk/vermin/blob/master/tests/testutils.py#L65). It yields an instance of a `SourceVisitor` which has analyzed the source code, so you can ask for minimum versions, language features, text to be output etc. Would that be useful?

**Comment by gousaiyang** [comment]
This is useful, especially for detecting a certain type of feature. But it could be more useful if we can set the verbosity level from `visit()` so that `output_text()` can be seen. The verbosity comes from `self.__config` which probably only comes from CLI as for now. Perhaps in the future configuration could be specified from CLI, from API or from a config file in the project directory like `vermin.ini`, if necessary.

I acknowledge that the most common use of vermin when analysing a multi file code base is to use the CLI, so the API could be thought as a simplified feature (or an experimental feature). If we need to programmatically analyze the report, we may want to use the API or the machine parseable output proposed by #48.

**Comment by netromdk** [comment]
I will expose the `visit()` as well. And it is the plan to do a parsable output once the format is agreed upon.

You can actually use the config already now with `detect()`:
```py
>>> import vermin as V
>>> V.detect("a = long(1)")
[(2, 0), None]
>>> c = V.Config.get()
>>> c.add_exclusion("long")
>>> V.detect("a = long(1)")
[(0, 0), (0, 0)]
```

**Comment by netromdk** [comment]
I've now also exposed the `visit()` function from the module, which enables you to do things like:
```py
>>> import vermin as V
>>> c = V.Config.get()
>>> c.set_verbose(3)
>>> v = V.visit("a = long(1)")
>>> v.minimum_versions()
[(2, 0), None]
>>> print(v.output_text(), end="")
L1: long is a v2 feature
L1: 'long' member requires 2.0, !3
>>> v.longv2()
True
```

**Comment by netromdk** [comment]
Furthermore, I've converted `Config` to not be a singleton anymore, which has been bugging me for a while anyway, and this makes the interface clearer:
```py
>>> import vermin as V
>>> V.detect("a = long(1)")

>>> c = V.Config()
>>> c.add_exclusion("long")
>>> V.detect("a = long(1)", config=c)
[(0, 0), (0, 0)]

>>> v = V.visit("import zoneinfo", config=c)
>>> v.minimum_versions()
[None, (3, 9)]
>>> v.modules()
['zoneinfo']
>>> len(v.output_text()) == 0
True

>>> c.set_verbose(3)
>>> v = V.visit("import zoneinfo", config=c)
>>> v.minimum_versions()
[None, (3, 9)]
>>> print(v.output_text(), end="")
L1: 'zoneinfo' module requires !2, 3.9
>>> v.modules()
['zoneinfo']
```

**Comment by netromdk** [comment]
It's been merged to master now.

https://github.com/netromdk/vermin#api-experimental
