### ISSUE TITLE
False positive rule matching

### ISSUE THREAD

**Issue by gousaiyang** [netromdk/vermin#53]
This code snippet

```python
import os
s = 'a'
s.replace('b', 'c')
```

is incorrectly triggering the `os.replace` rule.

Another example:

```python
import typing
ping.Final
```

Substitute `ping` with any suffix of `typing` and you will reproduce the bug (i.e. `typing.Final` incorrectly detected). This looks like an incorrect implementation of suffix matching somewhere. If the `import` statement is commented out, the bug does not happen.

**Environment:**
 - Vermin version 0.10.5

**Comment by netromdk** [comment]
Thanks. I will look into it.
