### ISSUE TITLE
Only show violated rules when target version is given

### ISSUE THREAD

**Issue by gousaiyang** [netromdk/vermin#57]
When the `--target` argument is given, we expect `vermin` to work more like a linter: it has a predefined goal, matches some rules and report violations (and set exit code to 0 or 1 accordingly). Typically linters emit as few output lines as possible when there is no violation found, and only display violated rules when found. This helps users spot rule violations more easily, compare this:

```console
$ python3 vermin.py -t=2.7 -t=3.0 --format parsable .
/path/to/vermin/misc/travis/after_success.sh:4:7: error: invalid syntax: if [[ $TRAVIS_PYTHON_VERSION != 2.7 && $TRAVIS_PYTHON_VERSION != 3.4 ]]; then
/path/to/vermin/misc/travis/script.sh:4:7: error: invalid syntax: if [[ $TRAVIS_PYTHON_VERSION = 2.7 || $TRAVIS_PYTHON_VERSION = 3.4 ]]; then
(many lines omitted ...)
/path/to/vermin/runtests.py:8::2.7:3.1:'unittest.main(exit)'
/path/to/vermin/runtests.py:::2.7:3.1:
(many lines omitted ...)
:::2.7:3.1:
```
with this:

```console
$ python3 vermin.py -t=2.7 -t=3.0 --format parsable .
/path/to/vermin/runtests.py:8::2.7:3.1:'unittest.main(exit)'
/path/to/vermin/runtests.py:::2.7:3.1:
:::2.7:3.1:
```

We can either:

- Add a flag like `--only-show-violated` (maybe a shorter name) to do this, this flag only makes sense when `--target` is given
- Make this behavior to be the default when `--target` is given (this is backwards incompatible behavior change)

**Comment by netromdk** [comment]
While I understand your motivation, I don't want to make this the default behavior due to incompatibility and that the idea of the output is to show all results, while still providing an answer via exit code on whether the targets were hit. With that being said, it could make good sense to add a new argument for showing only violating results. Maybe `--violations`?

**Comment by gousaiyang** [comment]
`--violations` is good. I'm not sure if `-V` is good since many other tools use it as the short form of `--version`, but since it's not used by `vermin` as of now, it's acceptable.

**Comment by netromdk** [comment]
Yeah, I will actually add `-V` to also mean `--version` which is indeed more standard. Hm, well, maybe there would only be the long form `--violations` initially then. Is `-X` weird?

**Comment by gousaiyang** [comment]
`-X` is probably a bit weird since it usually means "eXtension" or "eXtra" or "eXecute".

**Comment by gousaiyang** [comment]
Actually "violation filtering" only makes sense when the given target is a "loose" comparsion (`--target=3.4-`) instead of a strict comparsion (`--target=3.4`). If a project's minimum version is higher than expected, any single rule that caused a higher minimum version is a violation. But if a project's minimum version is lower than expected and strict comparsion is used, the case is that, after looking at all the matched rules, all of them combined "violated" the strict comparsion (`== 3.4`) for the minimum version. If this happens, then maybe just showing all the matched rules (i.e. the current behavior) makes more sense.

**Comment by netromdk** [comment]
That's a good point. So if `--violations` and non-exact targets are specified, then it'll only show the findings with a higher minimum version? Like 3.5+ for your example above. This would also work when two non-exact targets are used at the same time, like `--target=2.5- --target=3.4-`.

**Comment by gousaiyang** [comment]
Yes, the whole point here is that when users are using `--violations`, they expect `vermin` to work as a linter, which emits as less output as possible, as long as it conveys enough information to diagnose all the problems found in their code.

Generally we may think of these possible output cases:

- **Show all**: the current behavior, display all files and all matched rule entries
- **Show violations**: only show matched rule entries with a higher minimum version; files without violating rules should not be displayed
- **Show no rules**: when no violating rules are found, do not show any files and matched rule entries (even if verbosity is at maximum), as if all of them are "filtered out"; this will only print the final versions verdict and possibly some tips

So when I rethink over the case in the previous comment, I actually find the "Show no rules" behavior better than "Show all". If a project's minimum version is actually 3.3 but target is specified as `3.4` (exact match), by showing no rules but only the final versions verdict, the user already knows that their project can even support more versions than expected (3.3+ in fact). This is sufficient information and there is no need to display all the rules matched in this case (and they can always see them without using `--violations`). This design decision also helps simplifying the design: **we can treat exact and non-exact targets in the same way for violation filtering**, the only difference is in the exit code.

Here is a list of expected behavior when there is one target (suppose it is `3.4`):

| Actual minimum version \ Target |                   exact (`3.4`)                   |      non-exact (`3.4-`)       |
|:-------------------------------:|:-------------------------------------------------:|:-----------------------------:|
|           !2, == 3.4            |               Show no rules, exit 0               | Same behavior as exact target |
|            !2, > 3.4            |       Show violations (3.5+ rules), exit 1        | Same behavior as exact target |
|            !2, < 3.4            |             Show no rules, **exit 1**             |   Show no rules, **exit 0**   |
|             ~2, ~3              | Show violations (3.5+ rules and ~2 rules), exit 1 | Same behavior as exact target |
|             ~2, !3              |        Show violations (~2 rules), exit 1         | Same behavior as exact target |
|             !2, !3              |          Show incompatible rules, exit 1          | Same behavior as exact target |

When there are two targets, the idea is similar. Here are a few example cases (suppose the targets are `2.6`, `3.2`):

| Actual minimum version |                      Behavior                       |
|:----------------------:|:---------------------------------------------------:|
|      > 2.6, > 3.2      | Show violations (2.7+ rules and 3.3+ rules), exit 1 |
|      > 2.6, < 3.2      |        Show violations (2.7+ rules), exit 1         |
|      < 2.6, > 3.2      |        Show violations (3.3+ rules), exit 1         |
|      < 2.6, < 3.2      |  Show no rules, exit according to exact/non-exact   |
|         !2, ~3         |  Show violations (!2 rules and 3.3+ rules), exit 1  |
|          ...           |                         ...                         |

An implementation could be: just treat the targets as non-exact and use them to filter each matched rule. Whether a target is exact or non-exact only affects the exit code.

The `--violations` flag is not allowed without specifying `--target` (or the corresponding config value). A config entry like `only_show_violations` will need to be added, with a negation CLI option like `--no-violations`.

---

A sample project and sample result:

```console
user@machine:/path $ ls
file1.py  file2.py
user@machine:/path $ cat file1.py
import enum
bytes.maketrans()
all()
user@machine:/path $ cat file2.py
enumerate()
user@machine:/path $ vermin -vvv --backport enum --target=2.6- --target=3.2- .
Detecting python files..
Analyzing 2 files using 8 processes..
!2, 3.3      /path/file1.py
  L1 C7: 'enum' module requires 2.4, 3.3
  L2: 'bytes.maketrans' member requires !2, 3.1
  L3 C0: 'all' member requires 2.5, 3.0

2.3, 3.0     /path/file2.py
  L1 C0: 'enumerate' member requires 2.3, 3.0

Minimum required versions: 3.3
Incompatible versions:     2
Target versions not met:   2.6-, 3.2-
user@machine:/path $ vermin -vvv --backport enum --target=2.6- --target=3.2- --violations .
Detecting python files..
Analyzing 2 files using 8 processes..
!2, 3.3      /path/file1.py
  L1 C7: 'enum' module requires 2.4, 3.3
  L2: 'bytes.maketrans' member requires !2, 3.1

Minimum required versions: 3.3
Incompatible versions:     2
Target versions not met:   2.6-, 3.2-
```

**Comment by netromdk** [comment]
I started on this feature - still in rough shape but it's getting somewhere.

@gousaiyang what do we want to show when there are no violations and the exit code is `0`? Meaning, no violations were found and thus it's a success but the regular matching at the end of the program will state target wasn't met because minimum versions are `~2, ~3` (since all rules were filtered out since they didn't violate the target).

Example:
```console
% cat /tmp/test.py                                                                                                                                                                                                                                                          
import enum        # !2, 3.4
bytes.maketrans()  # !2, 3.1
all()              # 2.5, 3.0
enumerate()        # 2.3, 3.0
% ./vermin.py -vv --target=3.4- --violations /tmp/test.py ; echo $?
Detecting python files..
Analyzing using 8 processes..
~2, ~3       /tmp/test.py
Minimum required versions: ~2, ~3
Target versions not met:   3.4-
1
```

In this case, the last two lines shouldn't be shown as they are but instead something like:
```
Target versions not violated: 3.4-
```

And exit code `0`.

But otherwise I think it's shaping up pretty well:
```console
% ./vermin.py -vv --target=3.1- --violations /tmp/test.py ; echo $?
Detecting python files..
Analyzing using 8 processes..
!2, 3.4      /tmp/test.py
  'enum' module requires !2, 3.4

Minimum required versions: 3.4
Incompatible versions:     2
Target versions not met:   3.1-
1

% ./vermin.py -vv --target=2.5- --target=3.4- --violations /tmp/test.py ; echo $?
Detecting python files..
Analyzing using 8 processes..
!2, 3.4      /tmp/test.py
  'bytes.maketrans' member requires !2, 3.1
  'enum' module requires !2, 3.4

Minimum required versions: 3.4
Incompatible versions:     2
Target versions not met:   2.5-, 3.4-
1
```

Thoughts? Thanks!
Oh and please do share if you can think up some interesting border case examples to add to the test suites.

**Comment by gousaiyang** [comment]
> What do we want to show when there are no violations and the exit code is 0?

I think the internal calculation for minimum required versions could stay the same (as if no rules are filtered out), but only **hide** those filtered rules from being printed. So that `/tmp/test.py` is still `!2, 3.4` rather than `~2, ~3` when `--target=3.4- --violations` is specified. `~2, ~3` may look misleading to users. And if a file has no violations, I prefer not to see it at all in the result. For your previous case, my expected output is:

```console
% ./vermin.py -vv --target=3.4- --violations /tmp/test.py ; echo $?
Detecting python files..
Analyzing using 8 processes..
Minimum required versions: 3.4
Incompatible versions:     2
0
% ./vermin.py --format parsable --target=3.4- --violations /tmp/test.py ; echo $?
:::!2:3.4:
0
```

**Comment by netromdk** [comment]
I agree that it looks better that the output stays the same if there aren't any violations.

Hmm. It's going to be difficult to have both filtered and unfiltered results because I don't keep track of the ones filtered out for violations calculations. Unless that is exactly what should happen.. For violations, only the combined versions (totaled v2 and v3 for each file and finally for all files in the end) are needed and then restricting what's printed in verbose mode. This way the general results are not changed and can thus get printed like they've always been.

**Comment by gousaiyang** [comment]
It's still possible to filter out rules right at the beginning. If a file has all rules filtered out, then we filter out this whole file (not printed and not counted towards final result). If a file still have some unfiltered rules, those rules should be more "restrictive" than filtered ones and can be used to calculate the minimum version for that file. In this way, the only problem is that, if all files are "compliant", we have literally "no data" to calculate the final versions verdict. We only know that there are no violations. Displaying `~2, ~3` here would be misleading. We should either display the real final versions verdict as if violation filtering was not in place, or just say "no violations" without printing a final versions verdict.

**Comment by netromdk** [comment]
If it filters out rules like the current solution, and there are no violations, then you cannot have the output you write:
```console
% ./vermin.py -vv --target=3.4- --violations /tmp/test.py ; echo $?
Detecting python files..
Analyzing using 8 processes..
Minimum required versions: 3.4
Incompatible versions:     2
0
% ./vermin.py --format parsable --target=3.4- --violations /tmp/test.py ; echo $?
:::!2:3.4:
0
```

This is because the `!2, 3.4` is not known. Instead it might look like:
```console
% ./vermin.py -vv --target=3.4- --violations /tmp/test.py ; echo $?
Detecting python files..
Analyzing using 8 processes..
Target versions not violated: 3.4-
0
% ./vermin.py --format parsable --target=3.4- --violations /tmp/test.py ; echo $?
0
```

**Comment by netromdk** [comment]
I'm thinking I might need to calculate the final versions verdict anyway then.

**Comment by netromdk** [comment]
Upon retrospection I realized that the violated versions aren't needed at all: it only matters that it shows or doesn't show rule violations in the output text. So the implementation can be simplified a little bit. This also means that the minimum versions and targets checking will remain the same and extra tests aren't needed to cover those things since only the output text changes.

**Comment by gousaiyang** [comment]
Currently many language feature findings are not filtered because they are calling `self.__vvprint` and `self.__vvvprint` directly without going through the filter in `__add_versions_entity`. Maybe the code needs a bit of refactoring. Example: try `x: int` with `--violations --target=3.6`.

**Comment by netromdk** [comment]
Thanks. Yes, it's not done yet :-)

**Comment by netromdk** [comment]
Okay, now we are getting to something usable. It's handling what you mentioned and the checking has been substantially simplified (reducing excess/duplicate logic).

As an additional, I've added forced minimum `-vv` when `--violations` is specified, meaning it will be verbosity mode 2 without specifying it. This makes sense because the output text cannot be seen unless `verbose >= 2`. It is still possible to manually specify verbosity 2, 3, 4..

**Comment by gousaiyang** [comment]
I've tested this against some of my projects and I think the current implementation is pretty good.

**Comment by netromdk** [comment]
Thanks for feedback and testing, @gousaiyang!
I've merged to `dev` branch for inclusion in the next release.
