### ISSUE TITLE
False positive generalized unpacking detection with starred expression as assignment target

### ISSUE THREAD

**Issue by gousaiyang** [netromdk/vermin#63]
Starred expressions are allowed as assignment targets for Python < 3.5:

```console
root@f1b4a742d8fc:/# python3.4
Python 3.4.10 (default, Mar 29 2019, 18:50:06)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> *x, y = [1, 2, 3]
>>> x
[1, 2]
>>> y
3
>>> z = *x, y
  File "<stdin>", line 1
SyntaxError: can use starred expression only as assignment target
```

Currently `vermin` falsely report this case as 3.5+:

```python
>>> vermin.detect('*x, y = [1, 2, 3]')
[None, (3, 5)]
```
Maybe we need to mark some flags such as `self.__seen_assign_target` in `visit_Assign` and treat the `targets` attribute specially.

**Environment**
 - Vermin version 1.0.3

**Comment by netromdk** [comment]
Thanks. I will take a look at this.

**Comment by netromdk** [comment]
@gousaiyang I've pushed a fix to branch `issue_63`. Could you test it out before I merge it? Thanks!

**Comment by gousaiyang** [comment]
Three issues:

1. Assignment target with starred expression could also appear at for loops and comprehensions:

```python
for *x, in [[1]]: pass
[x for *x, in [[1]]]  # also dict, set, generator comprehensions
```

2. Starred items may be deeply nested (not just direct child nodes as processed by `ast.iter_child_nodes`):

```python
([x, *y], z) = ((1, 2), 3)
```

3. Suppressing detection for assignment targets also incorrectly suppressed detection for the expression part (right value):

```python
*x, *y = *u, *v
```

**Comment by netromdk** [comment]
I've pushed fixes to your feedback. Instead of keeping a boolean of whether a starred assignment target had been observed, I now instead keep track of all the starred left-hand side expressions to be able to distinguish left-hand and right-hand side expressions.

Could you check again? Thanks

**Comment by gousaiyang** [comment]
This looks correct. But maybe we can just ignore all `Starred(value=..., ctx=Store())` (right-hand side expressions have `ctx=Load()`)? Then we don't even have to keep track of all the `Starred` and even don't need to explicitly check for assignment statement / for loops / comprehension (since their assignment targets will just have `ctx=Store()`)?

Also we should report unpacking assignment (`*x, y = [1, 2, 3]`) as 3.0+ (see [PEP 3132](https://www.python.org/dev/peps/pep-3132/)).

**Comment by netromdk** [comment]
That was a great idea which simplifies things, and the tests still check out fine.

Yeah, so basically any `Starred` with `ctx=Store()` should report unpacking assignment 3+.

**Comment by netromdk** [comment]
I've pushed both changes to `issue_63` now. Ready for merge?

**Comment by gousaiyang** [comment]
It's good!

**Comment by netromdk** [comment]
Great. It's merged. Thanks again!
