### ISSUE TITLE
`--exclude` unusable due to a small bug

### ISSUE THREAD

**Issue by gousaiyang** [netromdk/vermin#68]
**Describe the bug**
Cannot use the `--exclude` CLI flag due an internal bug.

**To Reproduce**

```console
$ python3 vermin.py --exclude x test.py
Traceback (most recent call last):
  File "/path/to/vermin.py", line 4, in <module>
    main()
  File "/path/to/vermin/main.py", line 14, in main
    args = Arguments(sys.argv[1:]).parse(config)
  File "/path/to/vermin/arguments.py", line 289, in parse
    config.add_exclusion(self.__args[i + 1])
  File "/path/to/vermin/config.py", line 280, in add_exclusion
    self.__exclusions.add(name)
AttributeError: 'list' object has no attribute 'add'
```

**Environment**
 - Vermin version: 1.1.1

**Suggested fix**

The problem is due to [this](https://github.com/netromdk/vermin/blob/5566d87dbed25372ca0083dd4bbb6fb069838520/vermin/config.py#L49) and [this](https://github.com/netromdk/vermin/blob/5566d87dbed25372ca0083dd4bbb6fb069838520/vermin/config.py#L287). Either `Config.exclusions()` should always return a `set`, or use `self.__exclusions = set(other_config.exclusions())`.

**Comment by netromdk** [comment]
Thanks for noticing!
Yes, this happens exactly when adding an exclusion to a config after overriding it from another config. It's been fixed in `dev`.
