### ISSUE TITLE
False positive builtin name detection in exception handler body

### ISSUE THREAD

**Issue by gousaiyang** [netromdk/vermin#69]
**Describe the bug**
Names in exception handler body could be incorrectly determined as builtin features used.

**To Reproduce**

File:
```python
for file in ['foo']:
    try:
        1 / 0
    except ZeroDivisionError:
        print(file)
```

Result:

```
Detecting python files..
Analyzing using 8 processes..
2.0, !3      test.py
  print(expr) requires 2.0, 3.0
  L5 C14: 'file' member requires 2.0, !3

Minimum required versions: 2.0
Incompatible versions:     3
```

**Expected behavior**

Should not detect `file` as Python 2 builtin `file` member.

**Environment**
 - Vermin version: 1.1.1

**Additional context**
This is due to commit bd9ded9 for addressing #45. To match the current detection heuristics (outside of exception handlers), we should not look for builtin exceptions in the `body` attribute of an `ExceptHandler` node, but only look for them inside the `type` attribute.

It would also be better to recognize `file` as a user-defined name in this case. There are [many kinds for syntactic structures which create new variables (bind names) in Python](https://docs.python.org/3/reference/executionmodel.html#naming-and-binding):

- Assignment (regular assignment, augmented assignment, annotated assignment, walrus)
- `import` statements
- Function and class definitions (the function/class name is a variable in the containing scope)
- Function argument list (an argument is a local variable of the function)
- `for` loops and comprehensions
- `with ... as ...`
- `except ... as ...`
- And pattern matching in 3.10 may also bind names

**Comment by netromdk** [comment]
Thanks for reporting this.

I've made an initial fix for exception handlers and raise expressions: f915d38

You are right that it would be better to detect as a user-defined name. There are just a lot of cases and I'm worried about false positives, but some of the cases are already covered. Will look into it.

**Comment by netromdk** [comment]
Also checking `cause`: b204ad0

**Comment by gousaiyang** [comment]
For these cases:

- Regular assignment statement
- `for` loops and comprehensions
- `with ... as ...`

the assignment target can be more than a simple name. The variables created by such assignments are the simple names and starred names inside the target. For example, `for a, (*b, c[d+e::f(g)], h.i) in ...: pass` created two variables `a` and `b`.

**Comment by netromdk** [comment]
Thanks for reminding me! :)

**Comment by netromdk** [comment]
@gousaiyang okay, I think 1a9d761 should cover the user-defines of assignments and other cases noted above.

**Comment by gousaiyang** [comment]
There are some unhandled cases:

- Comprehensions: `[file() for file in [lambda: None]]` (`file` is scoped)
- `vararg` and `kwarg` attributes of function def arguments:
  - `def foo(*file): ...`
  - `def foo(**file): ...`
- Argument list of `lambda` functions: `(lambda file: file())(print)` (can be handled in the same way as regular function def)

Additionally, there are some other points which do not fully match the reality, but I think they are acceptable:

- For `for` loops and `with ... as ...`, the newly created variables are actually still alive outside the new nesting level (it's a new context rather than a new scope). For example,
```python
for file in [...]:
    ...
file()
```
and
```python
with ... as file:
    ...
file()
```
are actually using a user-defined `file` in the end. But your scoped approach may be better to avoid false positives, and it might be less common to use such variables outside of the context. So it's acceptable to me.

- Consider these expressions as assignment targets:
  - `x[(y := 1)]`
  - `x[[y for y in [1]]]`
  - `x[(lambda y: y)]`
 
The assignment targets themselves actually do not create new variables, but their child expressions inside the subscript are creating new variables (which can be scoped differently from the outer assignment target). There is inaccuracy in terms of scope, but it's acceptable to me as a kind of simplification. If we want to accurately determine the names created by an assignment target itself (not by its child expressions), we may need our own version of `ast.walk` which prunes `ast.Subscript` and `ast.Attribute` child branches right at the beginning to avoid seeing `ctx=Store()` nodes inside a child expression.

**Comment by netromdk** [comment]
I've added handling for comprehensions, vararg, kwarg, and lambda args: 7b4cdca

You're right about the user-defs and scopes of `for` and `with` but I feel that the less false positives that it finds is better than having more of them.

Each of those three expressions finds `y` as user-def in the current impl. Isn't that correct then?

**Comment by gousaiyang** [comment]
> Each of those three expressions finds y as user-def in the current impl. Isn't that correct then?

`y` is indeed user-def, but the scope might be different. For example, consider `[file() for w, x[[file for file in [1]][0]] in [(1, 1)]]`. This code is actually calling builtin `file`, despite the presence of a user-defined `file` in the inner comprehension (inside the subscript) which is irrelevant to the outer comprehension.

**Comment by netromdk** [comment]
I've added the new cases you mentioned: 97e7b1b

It uses a walker that ignores subscripts and attributes for code like `[file() for w, x[[file for file in [1]][0]] in [(1, 1)]]`.

And since the elements of comprehensions are visited first via AST order, I'm visiting the comprehension targets first to support that. This happens with `[file() for a, file in [1]]` which otherwise visits `ast.Call` first:
```
ListComp(elt=Call(func=Name(id='file', ctx=Load()), args=[], keywords=[]), generators=[comprehension(target=Tuple(elts=[Name(id='a', ctx=Store()), Name(id='file', ctx=Store())], ctx=Store()), iter=List(elts=[Constant(value=1)], ctx=Load()), ifs=[], is_async=0)])
| Call(func=Name(id='file', ctx=Load()), args=[], keywords=[])
| comprehension(target=Tuple(elts=[Name(id='a', ctx=Store()), Name(id='file', ctx=Store())], ctx=Store()), iter=List(elts=[Constant(value=1)], ctx=Load()), ifs=[], is_async=0)
```

**Comment by gousaiyang** [comment]
I think we can just use `comp_walk` instead of `ast.walk` for all complex assignment target cases:

- `visit_Assign`
- `__handle_for`
- `__handle_comprehensions`
- `visit_With`: `with ctx() as (file, file2): ...` is valid (`optional_vars` can be complex)

And then we may name it as `assign_target_walk` and the docstring can be something like "Walker that yields all names created by an assignment target (ignores `ast.Subscript` and `ast.Attribute` nodes)".

For other parts I think it's pretty good for now.

**Comment by netromdk** [comment]
Great. Then I think 4a6a94e is ready. Thanks again.

**Comment by gousaiyang** [comment]
It's great!
