### ISSUE TITLE
Can't understand `list[T]` annotation

### ISSUE THREAD

**Issue by Masynchin** [netromdk/vermin#83]
**Describe the bug**
Vermin can't understand `list[T]` annotation. It shows that minimal version is 3.0

**To Reproduce**
I run

~~~shell
vernim main.py
~~~

on `main.py`

~~~python
def main(arguments: list[str]):
    ...
~~~

**Expected behavior**
Show that minimal version is 3.9

**Environment (please complete the following information):**
 - Vermin version of 1.3.3
 - Python version of 3.10.2

**Comment by netromdk** [comment]
Hello @Masynchin.

If you enable evaluation of annotations via `--eval-annotations` then it yields the desired result:
```
annotations requires !2, 3.0
builtin generic type annotation (list[..]) requires !2, 3.9
```

The reason for this to be enabled explicitly is covered in the [caveats section](https://github.com/netromdk/vermin#caveats) of the README:
> Function and variable annotations aren't evaluated at definition time when `from __future__ import annotations` is used ([PEP 563](https://www.python.org/dev/peps/pep-0563/)). This is why `--no-eval-annotations` is on by default (since v1.1.1, https://github.com/netromdk/vermin/issues/66). If annotations are being evaluated at runtime, like using `typing.get_type_hints` or evaluating `__annotations__` of an object, `--eval-annotations` should be used for best results.

**Comment by Masynchin** [comment]
@netromdk Thanks a lot!
